const VideoType = {
	VIDEO_CONTROLS : 'VIDEO_CONTROLS',
	VIDEO_PLAY: 'VIDEO_PLAY',
	VIDEO_TIME: 'VIDEO_TIME',
	VIDEO_DATA : 'VIDEO_DATA',
	VIDEO_URL : 'VIDEO_URL',
	ADD_VIDEO_PIN_CLICK:'ADD_VIDEO_PIN_CLICK',
	LIVE_ALL_VIDEOS: 'LIVE_ALL_VIDEOS',
	EDIT_TARGET_VIDEO: 'EDIT_TARGET_VIDEO'
};

export default VideoType;