const VideoType = {
	VIDEO_CONTROLS : 'VIDEO_CONTROLS',
	VIDEO_PLAY: 'VIDEO_PLAY',
	VIDEO_TIME: 'VIDEO_TIME',
	VIDEO_DATA : 'VIDEO_DATA',
	ADD_VIDEO_PIN_CLICK:'ADD_VIDEO_PIN_CLICK'
};

export default VideoType;