const GeocoderType = {
	FETCH_INPUT_LOCATION_SUCCESS: 'FETCH_INPUT_LOCATION_SUCCESS',
	FETCH_BUSINESS_LOCATION_SUCCESS: 'FETCH_BUSINESS_LOCATION_SUCCESS',
	UPDATE_GEOLOCATION: 'UPDATE_GEOLOCATION'
};

export default GeocoderType;